# This workflow will clone a repository, create a virtual environment, install dependencies, and run a script every 15 minutes

name: amfi-irdai-bot-runner

on:  # Triggers the workflow
  # schedule:  # Uncomment for scheduled trigger (e.g., every 15 minutes)
  #   - cron: "*/15 * * * *"  # 
  workflow_dispatch  # Manual trigger for now

jobs:
  build:
    runs-on: ubuntu-latest  # This workflow will run on a Ubuntu virtual machine

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Create virtual environment
        run: python3 -m venv venv

      - name: Activate virtual environment
        run: source venv/bin/activate  # For Linux/macOS

      - name: Install dependencies (including playwright)
        run: pip install -r requirements.txt
             playwright install

      # - name: Install the project in editable mode (optional)
      #   run: python setup.py install  # Only if needed

      - name: Run the script
        run: python setup.py
